:start
esptool.exe --chip auto -p com39 -b 921600 write_flash --flash_mode dio --flash_size detect --flash_freq 40m 0x0 bootloader.bin 0x8000 partition-table.bin 0x10000 i2c_tools.bin
set ret=%ERRORLEVEL%
if %ret% equ 0 ( goto OK)
if %ret% neq 0 (goto ERR)


:ERR
@echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
@echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
@echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
@echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
goto DONE
:OK
@echo OKOKOKOKOKOKOKOOOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKO
@echo OKOKOKOKOKOKOKOOOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKO
@echo OKOKOKOKOKOKOKOOOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKO
@echo OKOKOKOKOKOKOKOOOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKOKO
@echo off
@echo "Project stopping..."
@echo "Press any key to continue!"
pause
@echo "Continuing..."
:DONE
goto start